apiVersion: v1
kind: Service
metadata:  
  name: vad-app-service
spec:
  selector:    
    app: vad-app
  type: NodePort
  ports:  
  - name: http
    port: 443
    targetPort: 443
    nodePort: 30036
    protocol: TCP